//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_Of_Work.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
