//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_Of_Work.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<decimal> StateTax { get; set; }
        public Nullable<decimal> StateInsurance { get; set; }
        public Nullable<decimal> NetPay { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
